name: py3.10
description: App Description
ignoreFiles: .git venv
modules:
- name: flask
  language: python3.10
  web: flask
  description: Module description
  functions:
  - name: entry
    entry: entry.py
    description: the entry point for the function